Add `--all` flag to validate-spice script

diff --git a/validate-spice b/validate-spice
--- a/validate-spice
+++ b/validate-spice
@@ -1,13 +1,17 @@
 #!/bin/bash
 
-USAGE="Usage: ./validate-spice UUID"
+USAGE="Usage:"
+USAGEUUID="./validate-spice UUID"
+USAGEALL="./validate-spice --all"
 
 if [ $# -ne 1 ] ; then
     echo $USAGE
+    echo $USAGEUUID
+    echo $USAGEALL
     exit 1;
 fi
 
-UUID=$1
+PARAMETER=$1
 check="\xE2\x9C\x94"
 missing=" "
 cross="\xE2\x9D\x8C"
@@ -18,94 +22,105 @@ parentDirName=$(basename -- "$(pwd)")
 xletType=$(echo "$parentDirName" | cut -f3 -d '-')
 xletType="${xletType::-1}"
 
-# check if UUID exists
-if [ ! -d "$UUID" ]; then
-    echo "$UUID does not exist"
-    exit 1;
-fi
+# function with checks for an xlet
+function validate_xlet {
+    UUID=$1
+    cd $UUID
 
-
-cd $UUID
-
-# Check if info, screenshot files exist
-for file in "info.json" "screenshot.png"
-do
-    if [ ! -f $file ]; then
-        echo -e "[$missing] Missing file: $UUID/$file"
-        valid=false
-    fi
-done
-
-# Check if icon.png exists in root directory
-for iconFile in "icon.png" "files/$UUID/icon.png"
+    # Check if info, screenshot files exist
+    for file in "info.json" "screenshot.png"
     do
-    if [ ! -f $iconFile ]; then
-        echo -e "[$missing] Missing file: $UUID/$iconFile"
+        if [ ! -f $file ]; then
+            echo -e "[$missing] Missing file: $UUID/$file"
+            valid=false
+        fi
+    done
+
+    # Check if icon.png exists in root directory
+    for iconFile in "icon.png" "files/$UUID/icon.png"
+        do
+        if [ ! -f $iconFile ]; then
+            echo -e "[$missing] Missing file: $UUID/$iconFile"
+            valid=false
+        else
+            # check if icon is square
+            iconWidth=$(identify -format '%w' $iconFile)
+            iconHeight=$(identify -format '%h' $iconFile)
+            if [ $iconWidth != $iconHeight ]; then
+                echo -e "[$missing] icon.png of $UUID has to be square"
+                valid=false
+            fi
+        fi
+    done
+
+    # Check if UUID/files directory exists
+    UUIDfilesUUIDDirExists=false
+    if [ ! -d "files" ]; then
+        echo -e "[$missing] Missing directory: $UUID/files"
         valid=false
     else
-        # check if icon is square
-        iconWidth=$(identify -format '%w' $iconFile)
-        iconHeight=$(identify -format '%h' $iconFile)
-        if [ $iconWidth != $iconHeight ]; then
-            echo -e "[$missing] icon.png of $UUID has to be square"
+        # check if UUID/files is "empty"
+        countFilesInFiles=$(ls -A files | wc -l)
+        if [ $countFilesInFiles != 1 ]; then
+            echo -e "[$missing] $UUID/files should contain ONLY the $UUID directory!"
             valid=false
         fi
     fi
-done
 
-# Check if UUID/files directory exists
-UUIDfilesUUIDDirExists=false
-if [ ! -d "files" ]; then
-    echo -e "[$missing] Missing directory: $UUID/files"
-    valid=false
-else
-    # check if UUID/files is "empty"
-    countFilesInFiles=$(ls -A files | wc -l)
-    if [ $countFilesInFiles != 1 ]; then
-        echo -e "[$missing] $UUID/files should contain ONLY the $UUID directory!"
-        valid=false
-    fi
-fi
-
-# Check if UUID/files/UUID directory exists
-if [ ! -d "files/$UUID" ]; then
-    echo -e "[$missing] Content of the spice has to be placed inside $UUID/files/$UUID"
-    valid=false
-else
-
-    # Check if metadata.json exists
-    metadataFile="files/$UUID/metadata.json"
-    if [ ! -f $metadataFile ]; then
-        echo -e "[$missing] Missing file: $metadataFile"
+    # Check if UUID/files/UUID directory exists
+    if [ ! -d "files/$UUID" ]; then
+        echo -e "[$missing] Content of the spice has to be placed inside $UUID/files/$UUID"
         valid=false
     else
-        # check UUID in metadata
-        metadataUUID=$(grep '"uuid"' $metadataFile | grep '"'$UUID'"' | wc -c)
-        if [ $metadataUUID == 0 ]; then
-            echo -e "[$missing] uuid in metadata != $UUID -- UUID directory name must be equal to uuid in metadata.json!"
+
+        # Check if metadata.json exists
+        metadataFile="files/$UUID/metadata.json"
+        if [ ! -f $metadataFile ]; then
+            echo -e "[$missing] Missing file: $metadataFile"
             valid=false
+        else
+            # check UUID in metadata
+            metadataUUID=$(grep '"uuid"' $metadataFile | grep '"'$UUID'"' | wc -c)
+            if [ $metadataUUID == 0 ]; then
+                echo -e "[$missing] uuid in metadata != $UUID -- UUID directory name must be equal to uuid in metadata.json!"
+                valid=false
+            fi
+
+            # check for dangerous flag in metadata
+            dangerousFlag=$(grep '"dangerous"' $metadataFile | wc -c)
+            if [ $dangerousFlag != 0 ]; then
+                echo -e "[$missing] dangerous flag in $UUID/metadata.json has to be removed!"
+                valid=false
+            fi
         fi
 
-        # check for dangerous flag in metadata
-        dangerousFlag=$(grep '"dangerous"' $metadataFile | wc -c)
-        if [ $dangerousFlag != 0 ]; then
-            echo -e "[$missing] dangerous flag in $UUID/metadata.json has to be removed!"
+        # Check if applet.js/desklet.js/extension.js exists
+        file="files/$UUID/$xletType.js"
+        findFile=$(find files/$UUID -name "$xletType.js")
+        if [ "$findFile" == "" ]; then
+            echo -e "[$missing] $UUID/$file -- Missing file!"
             valid=false
         fi
     fi
 
-    # Check if applet.js/desklet.js/extension.js exists
-    file="files/$UUID/$xletType.js"
-    findFile=$(find files/$UUID -name "$xletType.js")
-    if [ "$findFile" == "" ]; then
-        echo -e "[$missing] $UUID/$file -- Missing file!"
-        valid=false
+
+    if [ "$valid" == true ]; then
+        echo -e "$check $check $check $check $check $UUID is valid!"
+    else
+        echo -e "$cross $cross $cross $cross $cross Please fix the issues in $UUID, which are mentioned above! $cross $cross $cross $cross $cross"
     fi
-fi
 
+    cd ..
+}
 
-if [ "$valid" == true ]; then
-    echo -e "$check $check $check $check $check $UUID is valid!"
-else
-    echo -e "$cross $cross $cross $cross $cross Please fix the issues in $UUID, which are mentioned above! $cross $cross $cross $cross $cross"
+# check if PARAMETER is valid and run validate_xlet function
+if [ "$PARAMETER" == "--all" ]; then
+    for uuid in */; do
+        validate_xlet ${uuid%/}
+    done
+elif [ -d "$PARAMETER" ]; then
+    validate_xlet $PARAMETER
+else 
+    echo "$PARAMETER is not a valid parameter"
+    exit 1;
 fi
